name: CI - Product Manager

on:
    push:
        branches: [main, "feature/product-manager"]
    pull_request: 
        branches: [main]
jobs:
    build:
        name: Build et Lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout du code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'
                cache: 'npm'

            - name: Installer les dépendances
              run: npm install
            
            - name: Linting
              run: npm run lint
            
            - name: Build
              run: npm run build